### PR TITLE
Gameboard UI fix

### PR DESCRIPTION
**Pull request by iguannalin**
## Description

Updated Gameboard to new alpine/bulma UI

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by argaudreau** [comment]
Gameboard runs into an error at startup which prevents it from loading in the server:

```
ERROR (c_plugin.py:70 enable) Error enabling plugin=gameboard, No directory exists at '/Users/agaudreau/Documents/CALDERA/caldera/plugins/gameboard/static'
```

**Comment by iguannalin** [comment]
> Gameboard runs into an error at startup which prevents it from loading in the server:
> 
> ```
> ERROR (c_plugin.py:70 enable) Error enabling plugin=gameboard, No directory exists at '/Users/agaudreau/Documents/CALDERA/caldera/plugins/gameboard/static'
> ```

Good catch--I removed the `static/` folder but didn't catch this error since I was running the same instance. Fixed now!

**Review by argaudreau — CHANGES_REQUESTED** [review]
* It'd be nice to have this page auto refresh every 3 seconds like in other pages, so that the user doesn't have to re-select an operation to see the new score.
* The custom analytic modal needs a bit more information on it. For example, there's no indication that clicking save will kick off a blue operation. A description at the top of the modal would be useful, especially if it provides details or examples on what the query should look like. I'd also add a close button here in case users don't know they can click the background to dismiss it.
* The page needs to be more "compartmentalized". There's a lot of empty grey space, and because of that some of the elements seem randomly placed (like the External Detection button). Maybe add a line splitting the red/blue sides, or some card-like backgrounds to the score rows? As some inspiration I'd think of a scoreboard at a baseball game, something to make the page look more game-ified.

**Comment by iguannalin** [comment]
> * It'd be nice to have this page auto refresh every 3 seconds like in other pages, so that the user doesn't have to re-select an operation to see the new score.
> * The custom analytic modal needs a bit more information on it. For example, there's no indication that clicking save will kick off a blue operation. A description at the top of the modal would be useful, especially if it provides details or examples on what the query should look like. I'd also add a close button here in case users don't know they can click the background to dismiss it.
> * The page needs to be more "compartmentalized". There's a lot of empty grey space, and because of that some of the elements seem randomly placed (like the External Detection button). Maybe add a line splitting the red/blue sides, or some card-like backgrounds to the score rows? As some inspiration I'd think of a scoreboard at a baseball game, something to make the page look more game-ified.

I like the scoreboard idea! I'll explore that a bit more. About your second point, I'm not sure if creating a custom analytic should kick off a blue operation. From the old UI it seems that it passes a setting to the API, and I believe that from there it should show up on future operation command executions. I could be wrong and maybe @mchan143 can help answer this?

**Review by argaudreau — CHANGES_REQUESTED** [review]
I really like the new design! The layout looks a lot neater. A few things:

* The error rate table in the middle has a lot of padding/margin at the top so it isn't aligned with the scores. The "T" and "F" on the left has excess padding on the right too. 
* The lines going across each row aren't straight
Screen Shot 2021-12-13 at 1 00 15 PM
* On the add external detection modal, the input field isn't styled to match other inputs. 
  * On the same modal, maybe a horizontal radio group would be better than a slider for PID/GUID? I like that the slider is an easy one-click setting but it looks a little out of place on this form
* Are the fields in the facts modal ever to be edited? If not it'd be better not to use an input field to show those values. 
* I really like the suggested query addition! It looks a little cramped as a horizontal form at least on the Fact I was viewing. It'd be nice to have a button for each suggested query where it will open the Custom Analytic window and autopopulate the query field.  
Screen Shot 2021-12-13 at 1 12 01 PM
* When a blue op fails to detect/stop a red op step it says "Click for more details", but when I click it the Fact modal says "No other details to show". Can we prevent that modal from opening if there are no details on that step?

**Comment by iguannalin** [comment]
> * o

@argaudreau Fixed! I'd like to push back on the point about the input fields for the Facts modal, though. They don't ever get edited so they are in `readonly` mode, but I like that it's in a container and not completely disabled so it gives the option of selecting the text and copying/pasting if needed.

**Comment by argaudreau** [comment]
Looks great! Just a couple more things and we'll be good to merge:
* The Add External Detection modal's last input is a white input field, looks like it's just missing a `class="input is-small"`. 
* Can we add an arrow to the Suggested Queries dropdown like on the fact sources page in case people don't know that you can expand it?
* The Reason field might belong better above the Suggested Queries section, so when it's expanded that field doesn't get pinned to the bottom.
* Can you add an auto refresh like in the Operations or Agents page so this page will update in real time as operations run?

**Review by argaudreau — APPROVED** [review]
LGTM!

**Pull request merged**
